/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/ota/FOTAMPUUpdateSomeIPStubAdapter.hpp>
#include <v1/commonapi/ota/FOTAMPUUpdate.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace ota {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createFOTAMPUUpdateSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< FOTAMPUUpdateSomeIPStubAdapter<::v1::commonapi::ota::FOTAMPUUpdateStub>>(_address, _connection, _stub);
}

void initializeFOTAMPUUpdateSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.ota.FOTAMPUUpdate:v1_0:commonapi.ota.FOTAMPUUpdate",
         0x1010, 0x4, 1, 0);
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.ota.FOTAMPUUpdate:v1_0:commonapi.ota.FOTAMPUUpdate1",
         0x1010, 0x7, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "commonapi.ota.FOTAMPUUpdate:v1_0",
        &createFOTAMPUUpdateSomeIPStubAdapter);
}

INITIALIZER(registerFOTAMPUUpdateSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeFOTAMPUUpdateSomeIPStubAdapter);
}

} // namespace ota
} // namespace commonapi
} // namespace v1
