/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_OTA_FOTAMPU_Update_STUB_HPP_
#define V1_COMMONAPI_OTA_FOTAMPU_Update_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/commonapi/ota/FOTAMPUUpdate.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace ota {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service FOTAMPUUpdate. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class FOTAMPUUpdateStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual FOTAMPUUpdate {
 public:


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for FOTAMPUUpdate.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class FOTAMPUUpdateStubRemoteEvent
{
public:
    virtual ~FOTAMPUUpdateStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service FOTAMPUUpdate to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class FOTAMPUUpdateStub
    : public virtual CommonAPI::Stub<FOTAMPUUpdateStubAdapter, FOTAMPUUpdateStubRemoteEvent>
{
public:
    typedef std::function<void (FOTAMPUUpdate::MPUUpdateTaskBuildingResp _MPUUpdateTaskBuildingResp)> BldUpdtTaskReply_t;
    typedef std::function<void (std::string _MPUTransmitProgressResp)> StwrTrsmtPrgsReply_t;
    typedef std::function<void (FOTAMPUUpdate::MPUUpdateStopResp _MPUUpdateStopResp)> StopUpdtReply_t;
    typedef std::function<void (FOTAMPUUpdate::MPUInstallStartResp _MPUInstallStartResp)> StartInstReply_t;
    typedef std::function<void (std::string _MPUInstallResultResp)> ReqInstResultReply_t;
    typedef std::function<void (FOTAMPUUpdate::MPUStatusSwitchResp _MPUStatusSwitchResp)> SwitchABBankReply_t;
    typedef std::function<void (FOTAMPUUpdate::MPUGetStatusResp _MPUGetStatusResp)> GetUpdtTaskStatusReply_t;
    typedef std::function<void (std::string _MPUSwitchResultResp)> ReqSwitchResultReply_t;
    typedef std::function<void (FOTAMPUUpdate::MPUGetUpdateLogResp _MPUGetUpdateLogResp)> GetUpdtTaskLogReply_t;

    virtual ~FOTAMPUUpdateStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 9);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method BldUpdtTask.
    virtual void BldUpdtTask(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _MPUUpdateTaskBuildingReq, BldUpdtTaskReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method StwrTrsmtPrgs.
    virtual void StwrTrsmtPrgs(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _MPUTransmitProgressReq, StwrTrsmtPrgsReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method StopUpdt.
    virtual void StopUpdt(const std::shared_ptr<CommonAPI::ClientId> _client, FOTAMPUUpdate::MPUUpdateStopReq _MPUUpdateStopReq, StopUpdtReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method StartInst.
    virtual void StartInst(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _MPUInstallStartReq, StartInstReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method ReqInstResult.
    virtual void ReqInstResult(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _MPUInstallResultReq, ReqInstResultReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method SwitchABBank.
    virtual void SwitchABBank(const std::shared_ptr<CommonAPI::ClientId> _client, FOTAMPUUpdate::MPUStatusSwitchReq _MPUStatusSwitchReq, SwitchABBankReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method GetUpdtTaskStatus.
    virtual void GetUpdtTaskStatus(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _MPUGetStatusReq, GetUpdtTaskStatusReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method ReqSwitchResult.
    virtual void ReqSwitchResult(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _MPUSwitchResultReq, ReqSwitchResultReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method GetUpdtTaskLog.
    virtual void GetUpdtTaskLog(const std::shared_ptr<CommonAPI::ClientId> _client, FOTAMPUUpdate::MPUGetUpdateLogReq _MPUGetUpdateLogReq, GetUpdtTaskLogReply_t _reply) = 0;


    using CommonAPI::Stub<FOTAMPUUpdateStubAdapter, FOTAMPUUpdateStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<FOTAMPUUpdateStubAdapter, FOTAMPUUpdateStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<FOTAMPUUpdateStubAdapter, FOTAMPUUpdateStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef FOTAMPUUpdateStubRemoteEvent RemoteEventType;
    typedef ::v1::commonapi::ota::FOTAMPUUpdate StubInterface;
};

} // namespace ota
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_OTA_FOTAMPU_Update_STUB_HPP_
