/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef V1_COMMONAPI_OTA_FOTAMPU_Update_SOMEIP_DEPLOYMENT_HPP_
#define V1_COMMONAPI_OTA_FOTAMPU_Update_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace ota {
namespace FOTAMPUUpdate_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> MPUUpdateTaskBuildingRespDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> MPUUpdateStopReqDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> MPUUpdateStopRespDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> MPUInstallStartRespDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> MPUStatusSwitchReqDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> MPUStatusSwitchRespDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> MPUGetStatusRespDeployment_t;

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment
COMMONAPI_EXPORT extern ::v1::commonapi::ota::FOTAMPUUpdate_::MPUUpdateStopReqDeployment_t StopUpdt_MPUUpdateStopReqDeployment;
COMMONAPI_EXPORT extern ::v1::commonapi::ota::FOTAMPUUpdate_::MPUUpdateStopRespDeployment_t StopUpdt_MPUUpdateStopRespDeployment;
COMMONAPI_EXPORT extern ::v1::commonapi::ota::FOTAMPUUpdate_::MPUInstallStartRespDeployment_t StartInst_MPUInstallStartRespDeployment;
COMMONAPI_EXPORT extern ::v1::commonapi::ota::FOTAMPUUpdate_::MPUStatusSwitchReqDeployment_t SwitchABBank_MPUStatusSwitchReqDeployment;
COMMONAPI_EXPORT extern ::v1::commonapi::ota::FOTAMPUUpdate_::MPUStatusSwitchRespDeployment_t SwitchABBank_MPUStatusSwitchRespDeployment;
COMMONAPI_EXPORT extern ::v1::commonapi::ota::FOTAMPUUpdate_::MPUGetStatusRespDeployment_t GetUpdtTaskStatus_MPUGetStatusRespDeployment;

// Broadcast-specific deployments

} // namespace FOTAMPUUpdate_
} // namespace ota
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_OTA_FOTAMPU_Update_SOMEIP_DEPLOYMENT_HPP_
